### ISSUE TITLE
Error after updating to 12.1

### ISSUE THREAD

**Issue by jerobins** [offlinemark/dawtool#22]
Could not extract markers from TCP-S01E10.als : Cannot parse automation
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/dawtool/daw/ableton.py", line 279, in _parse_events_from_main_track
    master_track = ET.fromstring(master_track_chunk)
  File "/usr/local/lib/python3.13/xml/etree/ElementTree.py", line 1343, in XML
    return parser.close()
           ~~~~~~~~~~~~^^
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dawtool", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/lib/python3.13/site-packages/dawtool/__main__.py", line 19, in main
    proj.parse()
    ~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/dawtool/daw/ableton.py", line 206, in parse
    self._parse_automation(self.contents)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dawtool/daw/ableton.py", line 313, in _parse_automation
    events = self._parse_events_from_main_track(contents, main_track_name)
  File "/usr/local/lib/python3.13/site-packages/dawtool/daw/ableton.py", line 281, in _parse_events_from_main_track
    raise ValueError('Cannot parse automation')
ValueError: Cannot parse automation
[TCP-S01E10.zip](https://github.com/user-attachments/files/17467155/TCP-S01E10.zip)

**Comment by offlinemark** [comment]
Fixed in https://github.com/offlinemark/dawtool/commit/e92308940d8dd951989645b5c3e394f02196b515, thank you.
